kind: pipeline
name: tomcat8

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

volumes:
  - name: docker
    host:
      path: /var/cache/drone/${DRONE_REPO}/${DRONE_STAGE_NAME}

steps:
- name: setup
  image: alpine
  environment: &setup_env
    APP_VER: 8.5.55
    APP_VER_MAJOR: "${APP_VER/.*/}"
    APP_VER_MINOR: "${APP_VER%.*}"
    APP_VER_MINOR: "${APP_VER_MINOR#*.}"
    APP_VER_PATCH: "${APP_VER/*./}"
    IMAGE_FROM: "tomcat:${APP_VER}-jdk8-openjdk-slim"
    #MYSQL_CONNECTOR_J: 8.0.19
    MYSQL_CONNECTOR_J: 5.1.49
  commands:
    - echo -e -n "$${APP_VER}-$${DRONE_BUILD_NUMBER}" >> .tags
    - echo -e -n ",$${APP_VER}" >> .tags
    - echo -e -n ",$${APP_VER%.*}" >> .tags
    - echo -e -n ",$${APP_VER%%.*}" > .tags
    - echo -e -n ",latest" >> .tags

- name: publish
  image: plugins/docker
  environment:
    <<: *setup_env
  settings:
    repo: izdock/tomcat
    build_args_from_env:
    - IMAGE_FROM
    - APP_VER
    - APP_VER_MAJOR
    - APP_VER_MINOR
    - APP_VER_MINOR
    - APP_VER_PATCH
    - MYSQL_CONNECTOR_J
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
  volumes:
  - name: docker
    path: /var/lib/docker
  when:
    event: [push, tag]
    branch: master
