kind: pipeline
type: docker
name: tomcat10-amd64

environment:
  # https://hub.docker.com/_/tomcat
  IMAGE_FROM: "tomcat:10.1.30-jre17-temurin-noble"
  APP_VER: 10.1.30

trigger:
  event:
  - push
  - tag
  branch:
  - master

platform:
  os: linux
  arch: amd64

#concurrency:
#  limit: 1

volumes:
  - name: cache
    host:
      path: /var/cache/drone/${DRONE_REPO}/${DRONE_STAGE_NAME}

workspace:
  base: /drone
  path: src

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - /drone/docker

- name: setup
  image: alpine
  commands:
    - echo -e -n "$${APP_VER}-${DRONE_BUILD_NUMBER}" > .tags
    - echo -e -n ",$${APP_VER}" >> .tags
    - echo -e -n ",$${APP_VER%.*}" >> .tags
    - echo -e -n ",$${APP_VER%%.*}" >> .tags
    #- echo -e -n ",latest" >> .tags

- name: publish
  image: plugins/docker
  environment:
    APP_VER_BUILD: "${DRONE_BUILD_NUMBER}"
    APP_BUILD_COMMIT: "${DRONE_COMMIT_SHA:0:7}"
    APP_BUILD_DATE: "${DRONE_BUILD_FINISHED}"
  settings:
    repo: izdock/tomcat
    build_args_from_env:
    - IMAGE_FROM
    - APP_VER
    - MYSQL_JDBC_VER
    - APP_VER_BUILD
    - APP_BUILD_COMMIT
    - APP_BUILD_DATE
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - /drone/docker

- name: notify
  image: spotlightkid/drone-matrixchat-notify
  settings:
    homeserver: https://quantico.in
    roomid: "!UCuIdxzWsiiboEXriU:quantico.in"
    userid: "@gitbot:quantico.in"
    password:
      from_secret: MATRIX_PASSWORD
    markdown: 'yes'
    template: |
      [`${DRONE_REPO}`](${DRONE_BUILD_LINK}) build:[`#${DRONE_BUILD_NUMBER}`] tag:[`${DRONE_TAG}`] status:[**${DRONE_BUILD_STATUS}**]
    
---
kind: pipeline
type: docker
name: tomcat9-amd64

environment:
  # https://hub.docker.com/_/tomcat
  IMAGE_FROM: "tomcat:9.0.95-jre11-temurin-noble"
  APP_VER: 9.0.95
  ## stuck to 8.0.22 because error:
  ## [IDVariant::convertObject] Cannot convert from class: java.time.LocalDateTime, object is 2020-01-04T23:21:50
  #MYSQL_JDBC_VER: 8.0.22

trigger:
  event:
  - push
  - tag
  branch:
  - master

platform:
  os: linux
  arch: amd64

#concurrency:
#  limit: 1

volumes:
  - name: cache
    host:
      path: /var/cache/drone/${DRONE_REPO}/${DRONE_STAGE_NAME}

workspace:
  base: /drone
  path: src

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - /drone/docker

- name: setup
  image: alpine
  commands:
    - echo -e -n "$${APP_VER}-${DRONE_BUILD_NUMBER}" > .tags
    - echo -e -n ",$${APP_VER}" >> .tags
    - echo -e -n ",$${APP_VER%.*}" >> .tags
    - echo -e -n ",$${APP_VER%%.*}" >> .tags
    - echo -e -n ",latest" >> .tags

- name: publish
  image: plugins/docker
  environment:
    # FIXME: TEST variables expansion doesn't works
    #IMAGE_FROM: "tomcat:${APP_VER}-jdk8-openjdk-slim"
    #APP_VER_MAJOR: "${APP_VER/.*/}"
    #APP_VER_SHORT: "${APP_VER%.*}"
    #APP_VER_MINOR: "${APP_VER_SHORT/*./}"
    #APP_VER_PATCH: "${APP_VER/*./}"
    APP_VER_BUILD: "${DRONE_BUILD_NUMBER}"
    APP_BUILD_COMMIT: "${DRONE_COMMIT_SHA:0:7}"
    APP_BUILD_DATE: "${DRONE_BUILD_FINISHED}"
  settings:
    repo: izdock/tomcat
    build_args_from_env:
    - IMAGE_FROM
    - APP_VER
    - MYSQL_JDBC_VER
    - APP_VER_BUILD
    - APP_BUILD_COMMIT
    - APP_BUILD_DATE
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD

- name: rebuild-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - /drone/docker
